insert into QCSAMPLE.HAPLOID
(
HAPLOID_IID,
TEST_RESULT_IID,
GENE_LOCUS_LONG_NME,
TYPE_1_NME,
TYPE_2_NME,
OBJECT_TYPE_1_CDE,
OBJECT_TYPE_2_CDE,
TRANSLATED_IND,
TRANSLATED_FROM_CAT_CDE,
GENOME_DATABASE_NME,
DATABASE_VERSION_TXT,
TEST_INTERPRETATION_DTE,
CREATE_TS,
CREATE_BY_ID,
UPDATE_TS,
UPDATE_BY_ID
)
select 
	QCSAMPLE.SEQ_HAPLOID.NEXTVAL,
	tr.TEST_RESULT_IID,
	h.name as GENE_LOCUS_LONG_NME,
	h.a1_type as TYPE_1_NME,
	h.a2_type as TYPE_2_NME,
	null as OBJECT_TYPE_1_CDE, -- ws call
	null as OBJECT_TYPE_2_CDE, -- ws call
	'N' as TRANSLATED_IND,
	null as TRANSLATED_FROM_CAT_CDE,
	'IMGT-HLA' as GENOME_DATABASE_NME,
	null as DATABASE_VERSION_TXT,
	tr.TEST_DTE as TEST_INTERPRETATION_DTE,
	SYSTIMESTAMP as CREATE_TS,
	'BODS_LOAD' as CREATE_BY_ID,
	SYSTIMESTAMP as UPDATE_TS,
	'BODS_LOAD' as UPDATE_BY_ID
from QCSAMPLE.QCSAMPLE_TR_SYBASE_OTR_HAP h
inner join QCSAMPLE_TR_TEMP tr on tr.hla_hist_id = h.hla_hist_id;