insert into QCSAMPLE.SAMPLE_SOURCE(
SAMPLE_SOURCE_IID,
SAMPLE_SUBJECT_GUID,
SAMPLE_SOURCE_ID,
SUBJECT_CLASS_CDE,
RACE_CDE,
ETHNICITY_CDE,
SEX_CDE,
SAMPLE_SOURCE_STATUS_CDE,
REGISTRY_SOURCE_IND,
COMMENT_TXT,
CREATE_TS,
CREATE_BY_ID,
UPDATE_TS,
UPDATE_BY_ID
)
select QCSAMPLE.SEQ_SAMPLE_SOURCE.NEXTVAL as SAMPLE_SOURCE_IID,
null as SAMPLE_SUBJECT_GUID,
'QC_DRIVE' || e.QC_MASTER_LOT_ID as SAMPLE_SOURCE_ID,
'DONOR' as SUBJECT_CLASS_CDE,
null as RACE_CDE,
null as ETHNICITY_CDE,
null as SEX_CDE,
'ACTIVE' as SAMPLE_SOURCE_STATUS_CDE,
'N' as REGISTRY_SOURCE_IND,
null as COMMENT_TXT,
SYSTIMESTAMP as CREATE_TS,
'BODS_LOAD' as CREATE_BY_ID,
SYSTIMESTAMP as UPDATE_TS,
'BODS_LOAD' as UPDATE_BY_ID
from ETL_STAGE.QCSAMPLE_INV_EXCEL_DNA e
where e.Active = 1 and not exists (select * from QCSAMPLE.SAMPLE_SOURCE ss where ss.SAMPLE_SOURCE_ID = 'QC_DRIVE' || cast(e.SAMPLE_ID as number(9)));
commit;