create table ETL_STAGE.QCSAMPLE_INV_SYBASE_QC_DID
(
qc_did varchar2(50),
nmdp_did number,
lst_updt_dte timestamp(0),
cnt_hist number
)
tablespace ETL_STAGE
/

grant DELETE,INSERT,SELECT,UPDATE on ETL_STAGE.QCSAMPLE_INV_SYBASE_QC_DID to ETL_STAGE_APP_USER
/

grant SELECT on ETL_STAGE.QCSAMPLE_INV_SYBASE_QC_DID to ETL_STAGE_RO_USER
/
grant SELECT on ETL_STAGE.QCSAMPLE_INV_SYBASE_QC_DID to QCSAMPLE_APP_USER
/
grant SELECT on ETL_STAGE.QCSAMPLE_INV_SYBASE_QC_DID to QCSAMPLE
/
