insert into QCSAMPLE.MASTER_LOT (
MASTER_LOT_IID,
MASTER_LOT_ID,
SAMPLE_SOURCE_IID,
MASTER_LOT_STATUS_CDE,
SAMPLE_COLLECTION_DTE,
SAMPLE_SOURCE_AGE_NUM,
ORIGINAL_QTY,
ORIGINAL_QTY_UOM,
USED_QTY,
USED_QTY_UOM,
ESTIMATED_SAMPLE_QTY,
ESTIMATED_SAMPLE_QTY_UOM,
COMMENT_TXT,
CREATE_TS,
CREATE_BY_ID,
UPDATE_TS,
UPDATE_BY_ID
)
select QCSAMPLE.SEQ_MASTER_LOT.NEXTVAL,
lpad(replace(e.QC_MASTER_LOT_ID, 'QC', ''),6,'0') as MASTER_LOT_ID,
ss.SAMPLE_SOURCE_IID,
'ACTIVE' as MASTER_LOT_STATUS_CDE,
e.DATE_COLLECTED as SAMPLE_COLLECTION_DTE,
0 as SAMPLE_SOURCE_AGE_NUM,
e.TOTAL_VIALS as ORIGINAL_QTY,
'unit' as ORIGINAL_QTY_UOM,
e.VIALS_USED as USED_QTY,
'unit' as USED_QTY_UOM,
null as ESTIMATED_SAMPLE_QTY,
null as ESTIMATED_SAMPLE_QTY_UOM,
case when e.VOL_EXTRACTED like '%/%' 
    then (substr(e.VOL_EXTRACTED, 1, instr(e.VOL_EXTRACTED, '/', 1, 1) - 1) + substr(e.VOL_EXTRACTED, instr(e.VOL_EXTRACTED, '/', 1, 1) + 1, 100)) || ' mL in 2 conical tubes'
    else e.VOL_EXTRACTED || ' mL in 1 conical tube'
end as COMMENT_TXT,SYSTIMESTAMP as CREATE_TS,
'BODS_LOAD' as CREATE_BY_ID,
SYSTIMESTAMP as UPDATE_TS,
'BODS_LOAD' as UPDATE_BY_ID
from ETL_STAGE.QCSAMPLE_INV_EXCEL_CB e
inner join QCSAMPLE.SAMPLE_SOURCE ss on e.LOCAL_CBU_ID = ss.SAMPLE_SOURCE_ID
where e.LOCAL_CBU_ID is not null;
commit;