declare max_ml_id number;
begin
select max(master_lot_id) into max_ml_id from QCSAMPLE.MASTER_LOT; 
insert into QCSAMPLE.MASTER_LOT (
MASTER_LOT_IID,
MASTER_LOT_ID,
SAMPLE_SOURCE_IID,
MASTER_LOT_STATUS_CDE,
SAMPLE_COLLECTION_DTE,
SAMPLE_SOURCE_AGE_NUM,
ORIGINAL_QTY,
ORIGINAL_QTY_UOM,
USED_QTY,
USED_QTY_UOM,
ESTIMATED_SAMPLE_QTY,
ESTIMATED_SAMPLE_QTY_UOM,
COMMENT_TXT,
CREATE_TS,
CREATE_BY_ID,
UPDATE_TS,
UPDATE_BY_ID
)
select QCSAMPLE.SEQ_MASTER_LOT.NEXTVAL,
lpad(max_ml_id + ROWNUM, 6, '0') as MASTER_LOT_ID,
ml.SAMPLE_SOURCE_IID,
'ACTIVE' as MASTER_LOT_STATUS_CDE,
e.DATE_COLLECTED as SAMPLE_COLLECTION_DTE,
null as SAMPLE_SOURCE_AGE_NUM,
e.TOTAL_VIALS as ORIGINAL_QTY,
'unit' as ORIGINAL_QTY_UOM,
null as USED_QTY,
null as USED_QTY_UOM,
null as ESTIMATED_SAMPLE_QTY,
null as ESTIMATED_SAMPLE_QTY_UOM,
null as COMMENT_TXT,
SYSTIMESTAMP as CREATE_TS,
'BODS_LOAD' as CREATE_BY_ID,
SYSTIMESTAMP as UPDATE_TS,
'BODS_LOAD' as UPDATE_BY_ID
from ETL_STAGE.QCSAMPLE_INV_EXCEL_WB_1 e
inner join QCSAMPLE.MASTER_LOT ml on cast(ml.MASTER_LOT_ID as number) = cast(e.QC_MASTER as number);
commit;
end;