-- CANCEL_REASON
INSERT INTO ${ordersUser}.CANCEL_REASON (CANCEL_REASON_CDE,CANCEL_REASON_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('AE','Adverse event with GCSF',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.CANCEL_REASON (CANCEL_REASON_CDE,CANCEL_REASON_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('AG','Aliquots Gone',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.CANCEL_REASON (CANCEL_REASON_CDE,CANCEL_REASON_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('CA','Cancel Request',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.CANCEL_REASON (CANCEL_REASON_CDE,CANCEL_REASON_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('CB','Cord Infused',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.CANCEL_REASON (CANCEL_REASON_CDE,CANCEL_REASON_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('CC','Collection complete',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.CANCEL_REASON (CANCEL_REASON_CDE,CANCEL_REASON_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('CD','Cord destroyed or damaged',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.CANCEL_REASON (CANCEL_REASON_CDE,CANCEL_REASON_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('DC','DC declines to approach donor',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.CANCEL_REASON (CANCEL_REASON_CDE,CANCEL_REASON_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('DD','Permanently Deferred',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.CANCEL_REASON (CANCEL_REASON_CDE,CANCEL_REASON_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('DS','Damaged in Transit',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.CANCEL_REASON (CANCEL_REASON_CDE,CANCEL_REASON_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('DT','Discrepant Typing',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.CANCEL_REASON (CANCEL_REASON_CDE,CANCEL_REASON_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('DU','Discrepant Unit',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.CANCEL_REASON (CANCEL_REASON_CDE,CANCEL_REASON_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('IN','Cord Infused',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.CANCEL_REASON (CANCEL_REASON_CDE,CANCEL_REASON_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('IS','Inadequate sample/Low volume',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.CANCEL_REASON (CANCEL_REASON_CDE,CANCEL_REASON_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('LE','Labeling error',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.CANCEL_REASON (CANCEL_REASON_CDE,CANCEL_REASON_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('LS','Lost in Transit',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.CANCEL_REASON (CANCEL_REASON_CDE,CANCEL_REASON_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('MD','Medical director denied reqst',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.CANCEL_REASON (CANCEL_REASON_CDE,CANCEL_REASON_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('MI','Ineligible for this product',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.CANCEL_REASON (CANCEL_REASON_CDE,CANCEL_REASON_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('MP','Match Potential',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.CANCEL_REASON (CANCEL_REASON_CDE,CANCEL_REASON_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('NA','Not interested in this product',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.CANCEL_REASON (CANCEL_REASON_CDE,CANCEL_REASON_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('NC','IDM not completed',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.CANCEL_REASON (CANCEL_REASON_CDE,CANCEL_REASON_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('NE','NMDP request error',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.CANCEL_REASON (CANCEL_REASON_CDE,CANCEL_REASON_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('NI','Not Interested',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.CANCEL_REASON (CANCEL_REASON_CDE,CANCEL_REASON_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('NM','No Match',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.CANCEL_REASON (CANCEL_REASON_CDE,CANCEL_REASON_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('NR','No results recv, 30 days past',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.CANCEL_REASON (CANCEL_REASON_CDE,CANCEL_REASON_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('OD','Donor too old to participate',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.CANCEL_REASON (CANCEL_REASON_CDE,CANCEL_REASON_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('OT','Other',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.CANCEL_REASON (CANCEL_REASON_CDE,CANCEL_REASON_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('PC','Patient cond chg, no infusion',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.CANCEL_REASON (CANCEL_REASON_CDE,CANCEL_REASON_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('PD','Patient died, no infusion',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.CANCEL_REASON (CANCEL_REASON_CDE,CANCEL_REASON_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('QR','Cord Quarantined/TU',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.CANCEL_REASON (CANCEL_REASON_CDE,CANCEL_REASON_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('RO','Reserved for non NMDP search',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.CANCEL_REASON (CANCEL_REASON_CDE,CANCEL_REASON_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('SA','Send Letter A, Good match, pt not ready',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.CANCEL_REASON (CANCEL_REASON_CDE,CANCEL_REASON_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('SB','Send Letter B, Not the best match; different cord chosen',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.CANCEL_REASON (CANCEL_REASON_CDE,CANCEL_REASON_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('SC','Send Letter C, Not a match; cord incompatible',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.CANCEL_REASON (CANCEL_REASON_CDE,CANCEL_REASON_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('SD','Send Letter D, Patient Died',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.CANCEL_REASON (CANCEL_REASON_CDE,CANCEL_REASON_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('SE','Other cell source chosen',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.CANCEL_REASON (CANCEL_REASON_CDE,CANCEL_REASON_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('SO','Cord already shipped',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.CANCEL_REASON (CANCEL_REASON_CDE,CANCEL_REASON_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('SW','Switch Products',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.CANCEL_REASON (CANCEL_REASON_CDE,CANCEL_REASON_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('TC','TC decided against infusion',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.CANCEL_REASON (CANCEL_REASON_CDE,CANCEL_REASON_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('TE','TC request error',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.CANCEL_REASON (CANCEL_REASON_CDE,CANCEL_REASON_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('TS','Thawed in Transit',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.CANCEL_REASON (CANCEL_REASON_CDE,CANCEL_REASON_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('TU','Temp Unavailable',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.CANCEL_REASON (CANCEL_REASON_CDE,CANCEL_REASON_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('TX','Collection Cmplt, Dnr Recover',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.CANCEL_REASON (CANCEL_REASON_CDE,CANCEL_REASON_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('UC','Unable to contact',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.CANCEL_REASON (CANCEL_REASON_CDE,CANCEL_REASON_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('WD','Wrong donor draw',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.CANCEL_REASON (CANCEL_REASON_CDE,CANCEL_REASON_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('XP','Cord expired',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.CANCEL_REASON (CANCEL_REASON_CDE,CANCEL_REASON_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('SHE','Shipping error',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.CANCEL_REASON (CANCEL_REASON_CDE,CANCEL_REASON_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('SNA','Lab/Repository sample not available',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.CANCEL_REASON (CANCEL_REASON_CDE,CANCEL_REASON_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('RSO','Reserved for non NMDP search',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);

-- CENTRAL_LINE_PLACEMENT
INSERT INTO ${ordersUser}.CENTRAL_LINE_PLACEMENT (CENTRAL_LINE_PLACEMENT_CDE,CENTRAL_LINE_PLACEMENT_NME,CREATE_BY_ID,CREATE_TS,UPDATE_BY_ID,UPDATE_TS) VALUES ('PreCollect','Placement Required Prior to Collection',USER,SYSTIMESTAMP,USER,SYSTIMESTAMP);
INSERT INTO ${ordersUser}.CENTRAL_LINE_PLACEMENT (CENTRAL_LINE_PLACEMENT_CDE,CENTRAL_LINE_PLACEMENT_NME,CREATE_BY_ID,CREATE_TS,UPDATE_BY_ID,UPDATE_TS) VALUES ('Other','Other values not defined yet',USER,SYSTIMESTAMP,USER,SYSTIMESTAMP);

-- CENTRAL_LINE_STATUS
INSERT INTO ${ordersUser}.CENTRAL_LINE_STATUS (CENTRAL_LINE_STATUS_CDE,CENTRAL_LINE_STATUS_NME,CREATE_BY_ID,CREATE_TS,UPDATE_BY_ID,UPDATE_TS) VALUES ('InPlaceOK','In place, appropriate for collection',USER,SYSTIMESTAMP,USER,SYSTIMESTAMP);
INSERT INTO ${ordersUser}.CENTRAL_LINE_STATUS (CENTRAL_LINE_STATUS_CDE,CENTRAL_LINE_STATUS_NME,CREATE_BY_ID,CREATE_TS,UPDATE_BY_ID,UPDATE_TS) VALUES ('PreCollect','Placement required prior to collection',USER,SYSTIMESTAMP,USER,SYSTIMESTAMP);
INSERT INTO ${ordersUser}.CENTRAL_LINE_STATUS (CENTRAL_LINE_STATUS_CDE,CENTRAL_LINE_STATUS_NME,CREATE_BY_ID,CREATE_TS,UPDATE_BY_ID,UPDATE_TS) VALUES ('PeripheralOK','Peripheral venous access adequate for collection',USER,SYSTIMESTAMP,USER,SYSTIMESTAMP);
INSERT INTO ${ordersUser}.CENTRAL_LINE_STATUS (CENTRAL_LINE_STATUS_CDE,CENTRAL_LINE_STATUS_NME,CREATE_BY_ID,CREATE_TS,UPDATE_BY_ID,UPDATE_TS) VALUES ('InPlaceNotOK','In place, do not use for collection',USER,SYSTIMESTAMP,USER,SYSTIMESTAMP);

-- CLOSE_REASON
INSERT INTO ${ordersUser}.CLOSE_REASON (CLOSE_REASON_CDE,CLOSE_REASON_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('AE','Adverse event with GCSF',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.CLOSE_REASON (CLOSE_REASON_CDE,CLOSE_REASON_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('AG','Aliquots Gone',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.CLOSE_REASON (CLOSE_REASON_CDE,CLOSE_REASON_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('CA','Cancel Request',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.CLOSE_REASON (CLOSE_REASON_CDE,CLOSE_REASON_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('CB','Cord Infused',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.CLOSE_REASON (CLOSE_REASON_CDE,CLOSE_REASON_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('CC','Collection complete',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.CLOSE_REASON (CLOSE_REASON_CDE,CLOSE_REASON_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('CD','Cord destroyed or damaged',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.CLOSE_REASON (CLOSE_REASON_CDE,CLOSE_REASON_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('DC','DC declines to approach donor',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.CLOSE_REASON (CLOSE_REASON_CDE,CLOSE_REASON_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('DD','Permanently Deferred',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.CLOSE_REASON (CLOSE_REASON_CDE,CLOSE_REASON_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('DS','Damaged in Transit',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.CLOSE_REASON (CLOSE_REASON_CDE,CLOSE_REASON_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('DT','Discrepant Typing',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.CLOSE_REASON (CLOSE_REASON_CDE,CLOSE_REASON_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('DU','Discrepant Unit',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.CLOSE_REASON (CLOSE_REASON_CDE,CLOSE_REASON_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('IN','Cord Infused',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.CLOSE_REASON (CLOSE_REASON_CDE,CLOSE_REASON_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('IS','Inadequate sample/Low volume',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.CLOSE_REASON (CLOSE_REASON_CDE,CLOSE_REASON_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('LE','Labeling error',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.CLOSE_REASON (CLOSE_REASON_CDE,CLOSE_REASON_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('LS','Lost in Transit',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.CLOSE_REASON (CLOSE_REASON_CDE,CLOSE_REASON_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('MD','Medical director denied reqst',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.CLOSE_REASON (CLOSE_REASON_CDE,CLOSE_REASON_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('MI','Ineligible for this product',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.CLOSE_REASON (CLOSE_REASON_CDE,CLOSE_REASON_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('MP','Match Potential',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.CLOSE_REASON (CLOSE_REASON_CDE,CLOSE_REASON_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('NA','Not interested in this product',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.CLOSE_REASON (CLOSE_REASON_CDE,CLOSE_REASON_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('NC','IDM not completed',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.CLOSE_REASON (CLOSE_REASON_CDE,CLOSE_REASON_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('NE','NMDP request error',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.CLOSE_REASON (CLOSE_REASON_CDE,CLOSE_REASON_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('NI','Not Interested',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.CLOSE_REASON (CLOSE_REASON_CDE,CLOSE_REASON_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('NM','No Match',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.CLOSE_REASON (CLOSE_REASON_CDE,CLOSE_REASON_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('NR','No results recv, 30 days past',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.CLOSE_REASON (CLOSE_REASON_CDE,CLOSE_REASON_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('OD','Donor too old to participate',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.CLOSE_REASON (CLOSE_REASON_CDE,CLOSE_REASON_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('OT','Cord Deferred - Other Reasons',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.CLOSE_REASON (CLOSE_REASON_CDE,CLOSE_REASON_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('PC','Patient cond chg, no infusion',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.CLOSE_REASON (CLOSE_REASON_CDE,CLOSE_REASON_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('PD','Patient died, no infusion',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.CLOSE_REASON (CLOSE_REASON_CDE,CLOSE_REASON_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('QR','Cord Quarantined/TU',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.CLOSE_REASON (CLOSE_REASON_CDE,CLOSE_REASON_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('RO','Reserved for non NMDP search',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.CLOSE_REASON (CLOSE_REASON_CDE,CLOSE_REASON_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('SA','Send Letter A, Good match, pt not ready',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.CLOSE_REASON (CLOSE_REASON_CDE,CLOSE_REASON_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('SB','Send Letter B, Not the best match; different source chosen',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.CLOSE_REASON (CLOSE_REASON_CDE,CLOSE_REASON_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('SC','Send Letter C, Not a match; source incompatible',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.CLOSE_REASON (CLOSE_REASON_CDE,CLOSE_REASON_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('SD','Send Letter D, Patient Died',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.CLOSE_REASON (CLOSE_REASON_CDE,CLOSE_REASON_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('SE','Other cell source chosen',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.CLOSE_REASON (CLOSE_REASON_CDE,CLOSE_REASON_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('SO','Cord already shipped',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.CLOSE_REASON (CLOSE_REASON_CDE,CLOSE_REASON_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('SW','Switch Products',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.CLOSE_REASON (CLOSE_REASON_CDE,CLOSE_REASON_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('TC','TC decided against infusion',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.CLOSE_REASON (CLOSE_REASON_CDE,CLOSE_REASON_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('TE','TC request error',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.CLOSE_REASON (CLOSE_REASON_CDE,CLOSE_REASON_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('TS','Thawed in Transit',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.CLOSE_REASON (CLOSE_REASON_CDE,CLOSE_REASON_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('TU','Temp Unavailable',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.CLOSE_REASON (CLOSE_REASON_CDE,CLOSE_REASON_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('TX','Collection Cmplt, Dnr Recover',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.CLOSE_REASON (CLOSE_REASON_CDE,CLOSE_REASON_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('UC','Unable to contact',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.CLOSE_REASON (CLOSE_REASON_CDE,CLOSE_REASON_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('WD','Wrong donor draw',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.CLOSE_REASON (CLOSE_REASON_CDE,CLOSE_REASON_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('XP','Cord expired',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.CLOSE_REASON (CLOSE_REASON_CDE,CLOSE_REASON_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('SHE','Shipping error',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.CLOSE_REASON (CLOSE_REASON_CDE,CLOSE_REASON_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('SNA','Lab/Repository sample not available',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.CLOSE_REASON (CLOSE_REASON_CDE,CLOSE_REASON_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('23','Rejected',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.CLOSE_REASON (CLOSE_REASON_CDE,CLOSE_REASON_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('46','Completed',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.CLOSE_REASON (CLOSE_REASON_CDE,CLOSE_REASON_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('RSO','Reserved for non NMDP search',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);

-- DYNAMIC_FORM_FIELD_TYPE
INSERT INTO ${ordersUser}.DYNAMIC_FORM_FIELD_TYPE (FORM_FIELD_TYPE_CDE,FORM_FIELD_NME,CREATE_BY_ID,CREATE_TS,UPDATE_BY_ID,UPDATE_TS) VALUES ('INPUT','Input',USER,SYSTIMESTAMP,USER,SYSTIMESTAMP);
INSERT INTO ${ordersUser}.DYNAMIC_FORM_FIELD_TYPE (FORM_FIELD_TYPE_CDE,FORM_FIELD_NME,CREATE_BY_ID,CREATE_TS,UPDATE_BY_ID,UPDATE_TS) VALUES ('RADIO','Radio Button',USER,SYSTIMESTAMP,USER,SYSTIMESTAMP);
INSERT INTO ${ordersUser}.DYNAMIC_FORM_FIELD_TYPE (FORM_FIELD_TYPE_CDE,FORM_FIELD_NME,CREATE_BY_ID,CREATE_TS,UPDATE_BY_ID,UPDATE_TS) VALUES ('DROPDOWN','Drop down',USER,SYSTIMESTAMP,USER,SYSTIMESTAMP);
INSERT INTO ${ordersUser}.DYNAMIC_FORM_FIELD_TYPE (FORM_FIELD_TYPE_CDE,FORM_FIELD_NME,CREATE_BY_ID,CREATE_TS,UPDATE_BY_ID,UPDATE_TS) VALUES ('TEXT_AREA','Text Area',USER,SYSTIMESTAMP,USER,SYSTIMESTAMP);
INSERT INTO ${ordersUser}.DYNAMIC_FORM_FIELD_TYPE (FORM_FIELD_TYPE_CDE,FORM_FIELD_NME,CREATE_BY_ID,CREATE_TS,UPDATE_BY_ID,UPDATE_TS) VALUES ('DATE_PICKER','Date Picker',USER,SYSTIMESTAMP,USER,SYSTIMESTAMP);

-- DYNAMIC_FORM_TYPE
INSERT INTO ${ordersUser}.DYNAMIC_FORM_TYPE (DYNAMIC_FORM_TYPE_CDE,DYNAMIC_FORM_TYPE_NME,CREATE_BY_ID,CREATE_TS,UPDATE_BY_ID,UPDATE_TS) VALUES ('ORDER','orders-form',USER,SYSTIMESTAMP,USER,SYSTIMESTAMP);

-- FORM_MASTER_LIST
INSERT INTO ${ordersUser}.FORM_MASTER_LIST (FORM_IID,MASTER_CONTROL_FORM_ID,UNITE_FORM_NME,CREATE_BY_ID,CREATE_TS,UPDATE_BY_ID,UPDATE_TS) VALUES (1,'QA023306','Prescription_Verification',USER,SYSTIMESTAMP,USER,SYSTIMESTAMP);

-- ORDER_NOTIFICATION_TYPE
INSERT INTO ${ordersUser}.ORDER_NOTIFICATION_TYPE (ORDER_NOTIFICATION_TYPE_CDE,ORDER_NOTIFICATION_TYPE_NME,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('TASK','TASK',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.ORDER_NOTIFICATION_TYPE (ORDER_NOTIFICATION_TYPE_CDE,ORDER_NOTIFICATION_TYPE_NME,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('ALERT','ALERT',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);

-- ORDER_RELEASE_REASON
INSERT INTO ${ordersUser}.ORDER_RELEASE_REASON (RELEASE_REASON_CDE,RELEASE_REASON_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('PPR','Payment Received',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.ORDER_RELEASE_REASON (RELEASE_REASON_CDE,RELEASE_REASON_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('HUM','Humanitarian',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);

-- ORDER_STATUS
INSERT INTO ${ordersUser}.ORDER_STATUS (ORDER_STATUS_CDE,ORDER_STATUS_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('OPEN','Open Request',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.ORDER_STATUS (ORDER_STATUS_CDE,ORDER_STATUS_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('CLOSED','Closed Request',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.ORDER_STATUS (ORDER_STATUS_CDE,ORDER_STATUS_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('RESOLVED','Resolved Request',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.ORDER_STATUS (ORDER_STATUS_CDE,ORDER_STATUS_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('PENDING','Pending Request',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.ORDER_STATUS (ORDER_STATUS_CDE,ORDER_STATUS_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('REJECTED','Rejected Request',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.ORDER_STATUS (ORDER_STATUS_CDE,ORDER_STATUS_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('PENDREL','Pending Release',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);

-- ORDER_SUBJECT_FACTOR
INSERT INTO ${ordersUser}.ORDER_SUBJECT_FACTOR (ORDER_SUBJECT_FACTOR_CDE,ORDER_SUBJECT_FACTOR_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('PREVCT','Previously CT VAL',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.ORDER_SUBJECT_FACTOR (ORDER_SUBJECT_FACTOR_CDE,ORDER_SUBJECT_FACTOR_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('TRNSPLNTOC','Transplant Occurence',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.ORDER_SUBJECT_FACTOR (ORDER_SUBJECT_FACTOR_CDE,ORDER_SUBJECT_FACTOR_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('THERTYPE','Therapy Type',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);

-- ORDER_TYPE
INSERT INTO ${ordersUser}.ORDER_TYPE (ORDER_TYPE_CDE,ORDER_TYPE_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('CUSTOMER','CUSTOMER',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.ORDER_TYPE (ORDER_TYPE_CDE,ORDER_TYPE_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('FULFILL','FULFILL',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);

-- PROJECT
INSERT INTO ${ordersUser}.PROJECT (PROJECT_CDE,PROJECT_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('STSPRJ','State Street 1.0',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.PROJECT (PROJECT_CDE,PROJECT_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('BTCPRJ','Golden Gate 1.0 BioTherapies',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.PROJECT (PROJECT_CDE,PROJECT_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('B2CPRJ','Golden Gate 2.0 BioTherapies',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.PROJECT (PROJECT_CDE,PROJECT_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('REDPRJ','Redwood',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.PROJECT (PROJECT_CDE,PROJECT_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('TCPROJ','None',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.PROJECT (PROJECT_CDE,PROJECT_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('NMDPPRJ','NMDP Project',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.PROJECT (PROJECT_CDE,PROJECT_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('21DPRJ','21 Day Search',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.PROJECT (PROJECT_CDE,PROJECT_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('45DPRJ','45 Day Search',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.PROJECT (PROJECT_CDE,PROJECT_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('UU4PRJ','Ultra Urgent Phase 4',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.PROJECT (PROJECT_CDE,PROJECT_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('RPPPRJ','Referring Physician',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.PROJECT (PROJECT_CDE,PROJECT_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('PCTPRJ','Patient Customized Typing',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.PROJECT (PROJECT_CDE,PROJECT_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('PT1PRJ','T-Cell',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.PROJECT (PROJECT_CDE,PROJECT_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('COGPRJ','Children''s Oncology',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.PROJECT (PROJECT_CDE,PROJECT_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('AMLPRJ','AML/ALL Study',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.PROJECT (PROJECT_CDE,PROJECT_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('CD1PRJ','Contingency Drill 1',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.PROJECT (PROJECT_CDE,PROJECT_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('CE1PRJ','Contigency Event 1',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.PROJECT (PROJECT_CDE,PROJECT_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('PVMPRJ','PBSC vs. Marrow Randomized Tri',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.PROJECT (PROJECT_CDE,PROJECT_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('AD2PRJ','Accel Donation Proc, Phase II',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.PROJECT (PROJECT_CDE,PROJECT_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('RCCPRJ','Renal Cell Carcinoma Protocol',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.PROJECT (PROJECT_CDE,PROJECT_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('CTLPRJ','CTLs- cytotoxic T-lymphocytes',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.PROJECT (PROJECT_CDE,PROJECT_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('KIRPRJ','KIR:DS',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.PROJECT (PROJECT_CDE,PROJECT_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('RLTPRJ','Related',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);

-- PROPOSED_ORDER_TRACKING_STATUS
INSERT INTO ${ordersUser}.PROPOSED_ORDER_TRACKING_STATUS (PROPOSED_TRACKING_STATUS_CDE,PROPOSED_TRACKING_STATUS_NME,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('PENDING','Pending',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.PROPOSED_ORDER_TRACKING_STATUS (PROPOSED_TRACKING_STATUS_CDE,PROPOSED_TRACKING_STATUS_NME,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('APPROVED','Approved',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.PROPOSED_ORDER_TRACKING_STATUS (PROPOSED_TRACKING_STATUS_CDE,PROPOSED_TRACKING_STATUS_NME,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('REJECTED','Rejected',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.PROPOSED_ORDER_TRACKING_STATUS (PROPOSED_TRACKING_STATUS_CDE,PROPOSED_TRACKING_STATUS_NME,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('INFORMATIONAL','Informational',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);

-- SERVICE_ITEMIZATION_TYPE
INSERT INTO ${ordersUser}.SERVICE_ITEMIZATION_TYPE (SERVICE_ITEMIZATION_TYPE_CDE,SERVICE_ITEMIZATION_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('FULFILL','Itemization of Cust. Order to Fulfillment Order',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);

-- SERVICE_OPTION
INSERT INTO ${ordersUser}.SERVICE_OPTION (OPTION_CDE,OPTION_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('THERTYPE','Therapy Type',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.SERVICE_OPTION (OPTION_CDE,OPTION_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('PRODUCT','Product',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.SERVICE_OPTION (OPTION_CDE,OPTION_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('TRANSMTH','Transportation Method',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.SERVICE_OPTION (OPTION_CDE,OPTION_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('TRANSSRC','Transportation Source',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);

-- SERVICE_TYPE
INSERT INTO ${ordersUser}.SERVICE_TYPE (SERVICE_TYPE_CDE,SERVICE_TYPE_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('THERAPY','Therapy',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.SERVICE_TYPE (SERVICE_TYPE_CDE,SERVICE_TYPE_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('COLL','Collection',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.SERVICE_TYPE (SERVICE_TYPE_CDE,SERVICE_TYPE_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('TYP','Typing',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.SERVICE_TYPE (SERVICE_TYPE_CDE,SERVICE_TYPE_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('IDM','Infectious Disease Marker',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.SERVICE_TYPE (SERVICE_TYPE_CDE,SERVICE_TYPE_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('WKUP','Work-Up',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.SERVICE_TYPE (SERVICE_TYPE_CDE,SERVICE_TYPE_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('IS','Information Session',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.SERVICE_TYPE (SERVICE_TYPE_CDE,SERVICE_TYPE_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('PE','Physical Exam',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.SERVICE_TYPE (SERVICE_TYPE_CDE,SERVICE_TYPE_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('FS','Formal Search',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.SERVICE_TYPE (SERVICE_TYPE_CDE,SERVICE_TYPE_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('CT','Confirmatory Typing',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.SERVICE_TYPE (SERVICE_TYPE_CDE,SERVICE_TYPE_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('AU','Autologous Units',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.SERVICE_TYPE (SERVICE_TYPE_CDE,SERVICE_TYPE_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('COL','Collection',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.SERVICE_TYPE (SERVICE_TYPE_CDE,SERVICE_TYPE_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('FIL','Filgrastim',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.SERVICE_TYPE (SERVICE_TYPE_CDE,SERVICE_TYPE_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('TB','Tube of Blood',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.SERVICE_TYPE (SERVICE_TYPE_CDE,SERVICE_TYPE_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('TRANS','Transportation',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.SERVICE_TYPE (SERVICE_TYPE_CDE,SERVICE_TYPE_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('MISC','Miscellaneous',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.SERVICE_TYPE (SERVICE_TYPE_CDE,SERVICE_TYPE_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('SHP','Shipping',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.SERVICE_TYPE (SERVICE_TYPE_CDE,SERVICE_TYPE_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('PAF','PAF',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);

-- SOURCE_TYPE
INSERT INTO ${ordersUser}.SOURCE_TYPE (SOURCE_TYPE_CDE,SOURCE_TYPE_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('PATIENT','Patient',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.SOURCE_TYPE (SOURCE_TYPE_CDE,SOURCE_TYPE_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('DONOR','Donor',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.SOURCE_TYPE (SOURCE_TYPE_CDE,SOURCE_TYPE_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('CORD','Cord',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);

-- TRACKING
INSERT INTO ${ordersUser}.TRACKING (TRACKING_CDE,TRACKING_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('ORDERCOMMENTS','Order Comments and Additional Information',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.TRACKING (TRACKING_CDE,TRACKING_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('MFGTIMELINE','Manufacturing timeline ',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.TRACKING (TRACKING_CDE,TRACKING_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('QCSCHK','NMDP Quality Control Check',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.TRACKING (TRACKING_CDE,TRACKING_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('PATIENTCNSNTDATE','Patient Consent to Auto Therapy Process',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.TRACKING (TRACKING_CDE,TRACKING_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('QCSCHKACCNTCT','Contact at AC for QCS Review',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.TRACKING (TRACKING_CDE,TRACKING_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('QCSCHKACCNTCTPHN','Contact Phone Number at AC for QCS Review',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.TRACKING (TRACKING_CDE,TRACKING_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('ISBTDIN','Assigned ISBT128',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.TRACKING (TRACKING_CDE,TRACKING_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('ICCOLLCONFIRM','Apheresis date',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.TRACKING (TRACKING_CDE,TRACKING_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('PROPOSEDCOLLDTE','Proposed Collection Date',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.TRACKING (TRACKING_CDE,TRACKING_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('TARGETTHRPYCOMPDTE','Target Therapy Complete Date',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.TRACKING (TRACKING_CDE,TRACKING_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('PROPOSEDINFUSIONDTE','Proposed Infusion Date',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.TRACKING (TRACKING_CDE,TRACKING_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('APPRDTEDC','DC Med Director Approval Date',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.TRACKING (TRACKING_CDE,TRACKING_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('APPRDTENM','NMDP Med Director Approval Date',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.TRACKING (TRACKING_CDE,TRACKING_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('APPTDATE','Appointment Date',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.TRACKING (TRACKING_CDE,TRACKING_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('CBURCVD','CBU Received Date at TC',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.TRACKING (TRACKING_CDE,TRACKING_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('CBUTRGARRV','CBU Target Arrival Date at TC',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.TRACKING (TRACKING_CDE,TRACKING_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('CONFIRMED','Confirmed',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.TRACKING (TRACKING_CDE,TRACKING_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('CUSTVERRCV','Customer Verification Received Date',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.TRACKING (TRACKING_CDE,TRACKING_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('DETAILSTAGE','Order Detail Stage',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.TRACKING (TRACKING_CDE,TRACKING_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('DNRCLEAR','Donor Clearance Date',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.TRACKING (TRACKING_CDE,TRACKING_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('DNRCONSENT','Donor Consent-to-donate Given',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.TRACKING (TRACKING_CDE,TRACKING_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('DNRCONTPER','Person for Donor Contact',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.TRACKING (TRACKING_CDE,TRACKING_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('DNRCONTSAT','Satellite location for Donor Contact',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.TRACKING (TRACKING_CDE,TRACKING_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('FINALCBUREVIEW','Cord Unit review acceptability for shipment',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.TRACKING (TRACKING_CDE,TRACKING_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('INFORMDATE','Inform donor Date',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.TRACKING (TRACKING_CDE,TRACKING_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('LABNOTF','Lab Notify Date',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.TRACKING (TRACKING_CDE,TRACKING_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('NOMAKE','No Make',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.TRACKING (TRACKING_CDE,TRACKING_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('PREGTEST','Pregnancy Test Results',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.TRACKING (TRACKING_CDE,TRACKING_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('REPOSHIPDATE','Repository Ship Date',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.TRACKING (TRACKING_CDE,TRACKING_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('RESPRCVD','Response Received Date',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.TRACKING (TRACKING_CDE,TRACKING_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('RESULTSDATE','Results Received date',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.TRACKING (TRACKING_CDE,TRACKING_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('SAMPLLOC','Donor Sample Location',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.TRACKING (TRACKING_CDE,TRACKING_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('SENT','Request Sent',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.TRACKING (TRACKING_CDE,TRACKING_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('SHIPCOMPANY','Shipping Company',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.TRACKING (TRACKING_CDE,TRACKING_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('SHIPDATE','Ship Date',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.TRACKING (TRACKING_CDE,TRACKING_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('SPLRVERRCV','Supplier Verification Received Date',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.TRACKING (TRACKING_CDE,TRACKING_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('STAGE','Order Broad Stage',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.TRACKING (TRACKING_CDE,TRACKING_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('TCCOLLCONFIRM','TC collection confirm',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.TRACKING (TRACKING_CDE,TRACKING_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('TPLNTSTART','prep start date',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.TRACKING (TRACKING_CDE,TRACKING_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('TRANSDESC','Courier name (for donor)',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.TRACKING (TRACKING_CDE,TRACKING_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('TRANSMTHPCK','Who Picked Transportation Method',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.TRACKING (TRACKING_CDE,TRACKING_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('TRANSTRACKING','Tracking number (for cord)',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.TRACKING (TRACKING_CDE,TRACKING_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('WUPCANRSN','Workup Cancel Reason',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.TRACKING (TRACKING_CDE,TRACKING_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('WUPCOMP','Workup Complete Date',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.TRACKING (TRACKING_CDE,TRACKING_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('CONTRACTCTR','Contract Center',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.TRACKING (TRACKING_CDE,TRACKING_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('COMPINFOREQVERIFIED','Completed Information verfied',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.TRACKING (TRACKING_CDE,TRACKING_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('DUMNREQDATE','DUMN Request Date',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.TRACKING (TRACKING_CDE,TRACKING_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('CREDIT','Entity responsible for test results failed for finance credits',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.TRACKING (TRACKING_CDE,TRACKING_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('REPORCVDATE','Repository sample received Date',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.TRACKING (TRACKING_CDE,TRACKING_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('PARTIALTYPINGDATE','Date when partial typing results were reported',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.TRACKING (TRACKING_CDE,TRACKING_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('SHIPCONTAINER','The shipping container used for a Cord Unit when it is shipped to the TC.',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.TRACKING (TRACKING_CDE,TRACKING_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('PRDRCVDTDATE','Confirm product receipt',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.TRACKING (TRACKING_CDE,TRACKING_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('MFGCOMP','Manufacturing complete',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.TRACKING (TRACKING_CDE,TRACKING_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('THERSHIP','Therapy shipped',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.TRACKING (TRACKING_CDE,TRACKING_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('THERRCVD','Confirm therapy receipt',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.TRACKING (TRACKING_CDE,TRACKING_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('THERINFUSCONFIRM','Confirm therapy infusion',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.TRACKING (TRACKING_CDE,TRACKING_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('PRDCOLLCOMPLETE','Apheresis Completed',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.TRACKING (TRACKING_CDE,TRACKING_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('SHIPMATRCVD','Shipping Materials Received',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.TRACKING (TRACKING_CDE,TRACKING_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('PRDRELDATE','Product Released for Shipping',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.TRACKING (TRACKING_CDE,TRACKING_DESC,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('SHIPPACKCO','Package Material Shipping companies',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);

-- TRANSPORT_ADDRESS_TYPE
INSERT INTO ${ordersUser}.TRANSPORT_ADDRESS_TYPE (TRANSPORT_ADDRESS_TYPE_CDE,TRANSPORT_ADDRESS_TYPE_NME,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('CONTAINERPICKUP','Container Pickup',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.TRANSPORT_ADDRESS_TYPE (TRANSPORT_ADDRESS_TYPE_CDE,TRANSPORT_ADDRESS_TYPE_NME,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('CUST','CUST',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.TRANSPORT_ADDRESS_TYPE (TRANSPORT_ADDRESS_TYPE_CDE,TRANSPORT_ADDRESS_TYPE_NME,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('PRODUCTPICKUP','Product Pickup',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.TRANSPORT_ADDRESS_TYPE (TRANSPORT_ADDRESS_TYPE_CDE,TRANSPORT_ADDRESS_TYPE_NME,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('PRODUCTDLVY','Product Delivery',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.TRANSPORT_ADDRESS_TYPE (TRANSPORT_ADDRESS_TYPE_CDE,TRANSPORT_ADDRESS_TYPE_NME,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('CONTAINERDLVY','Container Delivery',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.TRANSPORT_ADDRESS_TYPE (TRANSPORT_ADDRESS_TYPE_CDE,TRANSPORT_ADDRESS_TYPE_NME,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('THERAPYPICKUP','Therapy Pickup',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.TRANSPORT_ADDRESS_TYPE (TRANSPORT_ADDRESS_TYPE_CDE,TRANSPORT_ADDRESS_TYPE_NME,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('THERAPYDLVY','Therapy Delivery',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);

-- TRANSPORT_DETAIL_METHOD
INSERT INTO ${ordersUser}.TRANSPORT_DETAIL_METHOD (TRANSPORT_DETAIL_METHOD_CDE,TRANSPORT_DETAIL_METHOD_NME,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('Hand','Hand carried',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.TRANSPORT_DETAIL_METHOD (TRANSPORT_DETAIL_METHOD_CDE,TRANSPORT_DETAIL_METHOD_NME,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('Door','Door-to-door',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.TRANSPORT_DETAIL_METHOD (TRANSPORT_DETAIL_METHOD_CDE,TRANSPORT_DETAIL_METHOD_NME,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('Cryo','Cryopreserved',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);

-- TRANSPORT_REQUEST_STATUS
INSERT INTO ${ordersUser}.TRANSPORT_REQUEST_STATUS (TRANSPORT_REQUEST_STATUS_CDE,TRANSPORT_REQUEST_STATUS_NME,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('NOSTRT','Not Started',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.TRANSPORT_REQUEST_STATUS (TRANSPORT_REQUEST_STATUS_CDE,TRANSPORT_REQUEST_STATUS_NME,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('REVREQ','Review Request',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.TRANSPORT_REQUEST_STATUS (TRANSPORT_REQUEST_STATUS_CDE,TRANSPORT_REQUEST_STATUS_NME,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('PLORDER','Place Order',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.TRANSPORT_REQUEST_STATUS (TRANSPORT_REQUEST_STATUS_CDE,TRANSPORT_REQUEST_STATUS_NME,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('REVITIN','Review Itinerary',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.TRANSPORT_REQUEST_STATUS (TRANSPORT_REQUEST_STATUS_CDE,TRANSPORT_REQUEST_STATUS_NME,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('SENDCONT','Send Container',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.TRANSPORT_REQUEST_STATUS (TRANSPORT_REQUEST_STATUS_CDE,TRANSPORT_REQUEST_STATUS_NME,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('CONFCONT','Confirm Container',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.TRANSPORT_REQUEST_STATUS (TRANSPORT_REQUEST_STATUS_CDE,TRANSPORT_REQUEST_STATUS_NME,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('DELIVERY','Delivery',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.TRANSPORT_REQUEST_STATUS (TRANSPORT_REQUEST_STATUS_CDE,TRANSPORT_REQUEST_STATUS_NME,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('CONFPUP','Confirm Product Pickup',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.TRANSPORT_REQUEST_STATUS (TRANSPORT_REQUEST_STATUS_CDE,TRANSPORT_REQUEST_STATUS_NME,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('CONFPDEL','Confirm Product Delivery',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.TRANSPORT_REQUEST_STATUS (TRANSPORT_REQUEST_STATUS_CDE,TRANSPORT_REQUEST_STATUS_NME,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('RETURNED','Returned',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);

-- TRANSPORT_TEMPERATURE
INSERT INTO ${ordersUser}.TRANSPORT_TEMPERATURE (TRANSPORT_TEMPERATURE_CDE,TRANSPORT_TEMPERATURE_NME,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('Room','Room Temperature',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.TRANSPORT_TEMPERATURE (TRANSPORT_TEMPERATURE_CDE,TRANSPORT_TEMPERATURE_NME,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('Cooled','Cooled',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);
INSERT INTO ${ordersUser}.TRANSPORT_TEMPERATURE (TRANSPORT_TEMPERATURE_CDE,TRANSPORT_TEMPERATURE_NME,UPDATE_TS,UPDATE_BY_ID,CREATE_TS,CREATE_BY_ID) VALUES ('Cryo','Cryopreserved',SYSTIMESTAMP,USER,SYSTIMESTAMP,USER);

commit;
